baseURL: https://codingforlearner.netlify.app
languageCode: en-us
title: Coding for Learner
paginate: 5
theme: "PaperMod"

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Coding for Learner
  description: "Learn Code with easy steps"
  keywords: [Blog, Portfolio, PaperMod]
  author: Alapakam Dorababu
  # author: ["Me", "You"] # multiple authors
  defaultTheme: auto # dark, light

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  # https://favicon.io/
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"

  cover:
    # hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    # hiddenInSingle: true # hide on single page
    # linkFullImage: true # open blog if click on cover image

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  homeInfoParams:
    Title: "Coding for Learner"
    Content: >
      👋 Welcome to Coding for Learner!

      - **Coding for Learner** is a welcoming blog tailored for beginners in the world of coding.
      With a user friendly approach, it provides easy-to-follow tutorials, tips, and insights to help newcomers grasp coding concepts effortlessly.Dive into the world of programming with confidence and guidance at Coding for Learner, where learning to code is made accessible and enjoyable.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10

    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20

    # - identifier: tags
    #   name: Tags
    #   url: /tags/
    #   weight: 30

    # - identifier: archives
    #   name: Archives
    #   url: /archives/
    #   weight: 40

    - identifier: search
      name: Search
      url: /search/
      weight: 50
